### ISSUE TITLE
Update SSO Missions with instructions for using index.html with booster

### ISSUE THREAD

**Issue by rhoads-zach** [fabric8-launch/appdev-documentation#332]
Update the SSO booster in each runtime with steps to use the index.html for interaction (ie. interaction section to use the included index.html page when available)
See info in related Jira ticket for the index.html change: https://issues.jboss.org/browse/OBST-304

**Comment by Ladicek** [comment]
For all other missions, we only describe the interaction using `curl`, but that's because using `curl` and using the webpage is exactly the same thing. In case of the SSO mission, the interaction using `curl` is different from using the webpage, so I agree we should describe both -- and we should also describe what's the difference. (Basically, the `curl` way is how programmatic interaction would be done, while the webpage is how user interface interaction would look like.)

**Comment by lavernw1** [comment]
Hi @Ladicek thanks for the update. I have run the SSO mission and noticed the difference in interaction for the web client using the Vert.x runtime. I'll look into adding an example. I've run the unmodified booster  on minishift.and got 401 not authorized when interacting via the web client HTTP API and greeting service. The single signon console admin login example worked as expected.

**Comment by lavernw1** [comment]
@Ladicek sorry typo. Error 404 is received when interacting via the web client HTTP API and greeting service with sso mission and current vert.x runtime.

**Comment by Ladicek** [comment]
@lavernw1 That sounds weird. @pmlopes is responsible for the SSO mission in general and the Vert.x SSO booster in particular, so he's probably the best one to speak with about such bugs.

**Comment by pmlopes** [comment]
@lavernw1 can you detail how you get 404, it doesn't seem normail, since the API did not change, just the static assets (index.html file)

**Comment by lavernw1** [comment]
@pmlopes  I was using the current vert.x guide https://appdev.openshift.io/docs/vertx-runtime.html#mission-secured-vertx

I followed the instructions in section 2.6 to Deploy RH SSO to your Single-node OpenShift Cluster using your launch.openshift.io Application.

In Step 2.6.5. Interact with the Secured Booster 
I interacted with the booster via the HTTP API and 
just wondered if there was additional setup to use the web client interface.  
 I got the message" bearer only applications are not authorized to initiate login" message when interacting on the page with HTTP Secured API  (login/logout buttons) and Greeting Service.
The Red Hat SSO page login works as expected.  Just also wanted to know if any differences interacting with the HTTP API via the web client or curl commands for that section.

**Comment by pmlopes** [comment]
This is a configuration issue, the sso client must be configured as public in keycloak, and the config exported and updated in 2-secret yml

**Comment by inoxx03** [comment]
@rhoads-zach @lavernw1 I propose closing this issue, as the AI's in here are also covered by #701.

**Comment by inoxx03** [comment]
Closing this issue due to overlap with #701
