### ISSUE TITLE
"Building and Deploying to OpenShift Build Process" sounds weird

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launch/appdev-documentation#672]
Appendix B of the Getting Started Guide is called "Building and Deploying to OpenShift Build Process", which sounds weird. This is after the recent heading changes; sorry for not catching it earlier.

**Comment by inoxx03** [comment]
@Ladicek I agree. This sentence, while not outright incorrect, seems highly ambiguous and slightly confusing.
IMHO, we seem to have 2 options here:

We could make it simpler, like: 

> Build and Deploy to Openshift

or, longer and more explicit, as in something like:

> Build and Deploy to Openshift: Build Process Description


Personally, I tend to favor the former. WDYT?

**Comment by inoxx03** [comment]
Fixed in PR #688

**Comment by inoxx03** [comment]
#688 was closed without merging due to outdated changes. Closing this issue as outdated.
