### ISSUE TITLE
Update all references to the docs repository to point to the new URL

### ISSUE THREAD

**Issue by inoxx03** [fabric8-launch/appdev-documentation#691]
NOTE:  in most cases listed below, the change does not break the links in question. IMHO, they should still be updated.

The new docs repo URL is: `https://github.com/fabric8-launch/appdev-documentation`
it replaces the old one: `https://github.com/openshiftio/appdev-documentation`

This replacement affects:
* all issue links in CHANGELOG.adoc (note-to-self:  update `generate_changelog.sh` to convert the issue links to attributes automatically)
* Links to releases (in the Releases page on GitHub and in CHANGELOG.adoc)
* Links to milestones from release pages 
* The _Releasing a New Version_ section of the Contrib Guide
* Repository link in the Contrib Guide (note-to-self:  this link should use the attribute instead of the explicit link. Will update!)
* 2 links  (L15 & L19) in `README.adoc`

**Comment by rhoads-zach** [comment]
fixed in #693
