### ISSUE TITLE
Minishift guide name impractical

### ISSUE THREAD

**Issue by tradej** [fabric8-launch/appdev-documentation#697]
Is it within our power to get the Minishift guide renamed to something else? I do not know the story behind the current one, but I consider it almost impossible to refer to in text. For example:

_See chapter XYZ of the Install and Configure the developers.redhat.com/launch Application on a Single-node OpenShift Cluster [Guide]._

The word _Guide_ is not even in the name of the book.

I don't know what the name should ideally be, but I think it shouldn't be more than a few words, and it should end with _Guide._

**Comment by rhoads-zach** [comment]
Updating 
 developers.redhat.com/launch -> Fabric8 Launcher

Also, adding intro section explaining what the Fabric8 Launcher is.

**Comment by tradej** [comment]
Please consider also updating the glossary if applicable/necessary.
