### ISSUE TITLE
Add documentation around the Launcher

### ISSUE THREAD

**Issue by inoxx03** [fabric8-launch/appdev-documentation#700]
Related to JIRA: // insert JIRA key here once it is created //

Concerns raised at last PM call about the lack of adequate docs around Fabric8 Launcher.
Docs team expected to address this next week (Oct 16th -20th) to leas enough time for review.

Addition info from the call:

Docs should also cover using the Launcher in greater detail
Docs should also include more detail on what RHOAR is.

Docs should cover how to use the runtimes:
* Creating applications from scratch (I know Zach has already done some work around this + scaffolding in the docs is in place, AFAIK)
* using different build/compile and deployment strategies

Side note: maybe consider adding a separate "Component | Launcher" label?

**Comment by inoxx03** [comment]
@cmoulliard Is there a JIRA issue open for this? If there is, would you please provide the JIRA key? I don't seem to be able to find the issue. Thanks.

**Comment by rhoads-zach** [comment]
fixed in #731
