### ISSUE TITLE
Refactor the Secured booster documentation

### ISSUE THREAD

**Issue by inoxx03** [fabric8-launch/appdev-documentation#701]
This issue is a blanket issue for the SSO booster docs refactor.
The partial tasks are now covered  by issues:
#716, #717, #718, #719, #720, #721 & #722

**Comment by Ladicek** [comment]
> Docs should focus on describing CLI-based interaction with the secured HTTP-API (using curl)

We actually already have this :-)

**Comment by heiko-braun** [comment]
We started to capture the required changes in a google doc, before consolidating it and submitting a PR: https://docs.google.com/document/d/10AR1-QW1J4UGphEXcy4c-bWulxH1Lo06XcjqkVCfyE4/edit#

**Comment by inoxx03** [comment]
Oh snap, you're right, @Ladicek :) Thanks for catching that. I've removed the item.

**Comment by inoxx03** [comment]
closing this as the tasks are now covered by individual issues (see description)
