### ISSUE TITLE
document how to deal with OpenShift quotas, especially on OpenShift Online Starter

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launch/appdev-documentation#714]
In our getting started docs, we show how to launch boosters to OpenShift Online, but (AFAIK) we don't tell that OSO has some stringent quotas (especially Starter).

I think the docs should lead users to 1. create a project using Launch (by "project", I mean OpenShift project, or namespace), 2. playing with it, 3. deleting the project before trying to launch another one. That way, one can be sure that nothing is left behind.

We can also list all kinds of resources that Launch creates in the OpenShift project: deployment + pods, service, route, build config + builds, and maybe more depending on the booster (e.g. ConfigMap). These can be deleted manually -- but that's probably less convenient.

CC @quintesse

**Comment by quintesse** [comment]
Yes, I think the latter option of cleaning up a project manually is just complicating things too much. Resource limits are mostly a problem with starter accounts where you won't be able to launch more than 2 boosters anyway (if that). And given the very strict limits starter accounts are just for trying things out anyway. So telling them to just delete the projects each time should be enough.

Now maybe for pro accounts we could explain how to remove things manually...

**Comment by rhoads-zach** [comment]
@Ladicek @quintesse do you mind looking a slight content change here:
https://github.com/fabric8-launch/appdev-documentation/pull/729/files#diff-89765e31cbdca890be1ea6876417c2b0R23

Any objections?

**Comment by quintesse** [comment]
No objection from me @rhoads-zach !

**Comment by Ladicek** [comment]
LGTM too.
