### ISSUE TITLE
Health check mission: Fix references to the `api/killme` endpoint in the docs.

### ISSUE THREAD

**Issue by inoxx03** [fabric8-launch/appdev-documentation#716]
It is a legitimate concert that the current name used for the endpoint that stops `name-service` could be considered inappropriate.
The runtime teams will discuss a suitable alternative and rename the endpoint.
Once done, we must change all references to the endpoint to reflect the name change.

**Comment by rhoads-zach** [comment]
@heiko-braun @cescoffier @cmoulliard @lholmquist Have you already updated your boosters to account for this? or is this still WIP?

**Comment by cescoffier** [comment]
The endpoint has been renamed into `/api/stop`. The button is now indicating `Stop Service`.

**Comment by lholmquist** [comment]
node booster has been updated

**Comment by cescoffier** [comment]
vert.x booster updated.

**Comment by metacosm** [comment]
Spring Boot booster updated.

**Comment by rhoads-zach** [comment]
@inoxx03 per #739 closing
