### ISSUE TITLE
Secured mission: ZIP booster deployment workflow

### ISSUE THREAD

**Issue by inoxx03** [fabric8-launch/appdev-documentation#717]
* Remove Launcher workflow
* add ZIP deployment workflow
** can be adapted from the existing ZIP workflow, if the SSO application is deployed from a git submodure
* Steps to manually deploy both applications to OSO Pro and OSCP
** Include note that the booster can not be deployed available on OSO Starter

**Comment by tradej** [comment]
Please investigate if the modules I wrote in #715 can be used for this issue.

**Comment by inoxx03** [comment]
Thank you @tradej, will investigate and reuse any existing content when suitable.

**Comment by heiko-braun** [comment]
I think all of this covered in  https://docs.google.com/document/d/1mum_guluetn9faHwyopU1QDWyNEfMG4gnAolR_cP40o/edit#heading=h.dq7ew3kzlw57

**Comment by tradej** [comment]
@heiko-braun, which heading do you have in mind? The link does not work for me.

**Comment by heiko-braun** [comment]
I've updated the link and didn't mean to link to any particular heading. The content I did refer is spread across "Deploying..." and "Interacting.."

**Comment by tradej** [comment]
The main PR is merged, we're awaiting feedback from the Spring Boot team about the deployment command. This is tracked in #751.
