### ISSUE TITLE
Secured mission: Add a Web form-based interaction workflow

### ISSUE THREAD

**Issue by inoxx03** [fabric8-launch/appdev-documentation#719]
WebUI steps should describe:

* Using the Keycloak/SSO web form to authenticate using pre-configured credentials.
* Using the HTTP API WebUI to make a request at the endpoint
//Consider adding screenshots for both.

**Comment by lavernw1** [comment]
@heiko-braun Thanks for the update. @inoxx03 will use the web interface to capture above screens mentioned for this section.

 Using the web interface
Your secured endpoint (see above) also contains a web interface for you to interact with it. You can access it using the endpoint address you retrieved previously (<SERVICE_HOST>)

http://<SERVICE_HOST>/index.html

Using the web interface you exercise the following to steps to see how security is enforced, authenticated happens and the token is requested and attached to an authenticated invocation.

Open the web interface and click on invoke. This will send an unauthenticated request to the greeting service. As a result the services responds with an HTTP 401 Unauthenticated“ status code
Authenticated yourself against Red Hat SSO by clicking the “Login” button. This will redirect you to the SSO server and request your credentials. Take a look at the pre-configured users in the SSO Realm Model above. Login as “Alice”
Once authenticated you will be redirected to the web interface, this time including a bearer token which can sen in the command line output at the bottom of the page.
Now try to invoke the greeting service by clicking “Invoke” again. You get no exception and JSON response payload will be displayed. This means the service accepted your bearer token and authorised access to the greeting service.

**Comment by rhoads-zach** [comment]
@heiko-braun this is in outside of the screen shots, working on it now.
