### ISSUE TITLE
Secured mission: Add documentation for running integration tests

### ISSUE THREAD

**Issue by inoxx03** [fabric8-launch/appdev-documentation#721]
The secured Booster docs requires a refactor of the integration tests section.
Related: Issue #711  
EDIT based on conversation with Heiko: 
The tests moved to the booster itself, whereas previously they did reside in the sso module.
Apart from that nothing should have changed (i.e. the instruction to the run the tests remain the same)

**Comment by lholmquist** [comment]
For node.js boosters, i usually remove this section since we don't have integration tests(yet)

**Comment by Ladicek** [comment]
For WildFly Swarm, the instructions are:

- deploy the SSO server: `oc apply -f service.sso.yaml`
- run the test, which requires knowing the SSO server url: `mvn clean verify -Popenshift,openshift-it -DSSO_AUTH_SERVER_URL=$(oc get route secure-sso -o jsonpath='https://{.spec.host}/auth')`
- undeploy the SSO server: `oc delete -f service.sso.yaml`)

Ideally, for Spring Boot and Vert.x the instructions would be the same, but I think they aren't there yet.

**Comment by inoxx03** [comment]
resolved in PR: #743
