### ISSUE TITLE
Spring Boot: Update release notes

### ISSUE THREAD

**Issue by lavernw1** [fabric8-launch/appdev-documentation#748]
1) Release notes need update for spring boot component versions (including Tomcat)
2) Note needed about JVM version required
3) Add table of SB specifications(features and version) as applicable 
Related JIRA for this issue is [OBST-462](https://issues.jboss.org/browse/OBST-462)

**Comment by inoxx03** [comment]
@lavernw1 FYI I've filed [OBST-464](https://issues.jboss.org/browse/OBST-464) to track the Tomcat version update based on the recent discussion.

**Comment by lavernw1** [comment]
@inoxx03 - Have collected the info from @cmoulliard, how do you want to proceed for completing the updates in the release notes.

**Comment by inoxx03** [comment]
@lavernw1 Thank you for collecting this information:)
I haven't yet migrated the release notes into their own repo (that's my AI for tomorrow:))
In the meantime, let's track these items in the release notes tracker JIRA.
I've filed a sub-task there in the RN tracker JIRA to cover these changes:  [OBST-489](https://issues.jboss.org/browse/OBST-489)

**Comment by inoxx03** [comment]
@lavernw1 Quick question: What exactly should the Note about JVM contain? Is it just an update to the required JVM version, or is there additional info that needs to be included? Thank you:)

**Comment by lavernw1** [comment]
@inoxx03 Need note or warning that SB tested and verified with Java 8.    (Not yet supported yet with Java 9 ). See [OBST-462](https://issues.jboss.org/browse/OBST-462).

**Comment by inoxx03** [comment]
@lavernw1 Thank you, I'll make sure to add a callout about this. 
FYI: We also have a _Supported Infrastructure Component Versions_ where we specify that the required Java version is 1.8.0 (that is, Java 8). AFAIK, other runtimes also support java 8 only, but i'm not sure.

**Comment by lavernw1** [comment]
Spring Boot component versions for Tomcat and JVM and related notes have been incorporated into the RN. This issue and  related JIRA OBST-462 can be closed.
