### ISSUE TITLE
WildFly Swarm: keycloak-authz-client Tech Preview status in Release Notes

### ISSUE THREAD

**Issue by tradej** [fabric8-launch/appdev-documentation#756]
Please add a note that `keycloak-authz-client` is Tech Preview for the WFS SSO booster in the Release Notes.

The note in docs is in the [Integration Tests module](https://raw.githubusercontent.com/fabric8-launch/appdev-documentation/master/docs/topics/proc_running-the-secured-booster-integration-tests.adoc).

relates #919

**Comment by inoxx03** [comment]
Resolved. Closing this issue.
