### ISSUE TITLE
http-api-spring-boot-pom.adoc is outdated and of dubious interest

### ISSUE THREAD

**Issue by metacosm** [fabric8-launch/appdev-documentation#761]
The document points to an outdated version of the POM file. More concerning, though, is the fact that we pick one example out of all the boosters without explaining why this example in particular, what makes it interesting, how to generalize the information extracted from it to the other boosters. It will also evolve soon as we are trying to put the common parts into a Spring Boot specific booster parent. For now, I would rather we remove this appendix as I'm not sure what it is trying to accomplish.

**Comment by tradej** [comment]
Just a note: Asciidoctor can apparently include parts of XML files by path, so we can use a real pom.xml that's stored in a (yet non-existent) location with other examples. That makes it easier to maintain than hunting various examples throughout the doc set. That's relevant only if we decide to keep the example, of course.

**Comment by lavernw1** [comment]
@metacosm wanted to keep this in the Appendix  to be consistent with other runtimes. What additional text is needed to accompany the snippet of the the POM file for Spring Boot?

**Comment by metacosm** [comment]
@lavernw1 I've explained some of my reasoning above already: the information is presented without context right now so it would need a lot of work to make it useful in my opinion…

**Comment by lavernw1** [comment]
@metacosm  Yes I agree.  Based on reviewing collective opinions from all  teams we have decided to remove the POM files for now and refactor them with more useful information.

**Comment by tradej** [comment]
Closing as the refactoring will be tracked in #858.
