### ISSUE TITLE
Explain why Spring Boot runtime is called Spring Boot Tomcat?

### ISSUE THREAD

**Issue by metacosm** [fabric8-launch/appdev-documentation#762]
Maybe it's explained somewhere outside of this documentation but it might be helpful to remind people reading the doc that the documentation (and RHOAR) only covers Spring Boot with embedded Tomcat / JWS (hence the name) as Spring Boot is not limited to Tomcat as far as servlet containers go.

**Comment by lavernw1** [comment]
@metacosm 
1) We are changing the runtime name to Spring Boot (removing tomcat from the title in issue [838](https://github.com/fabric8-launch/appdev-documentation/issues/838)) 
2) Given we change the name in [1] the runtime details section does not address your comment regarding RHOAR  only covers Spring Boot with embedded tomcat/JWS. 
Our current wording in runtime details:  
Spring Boot Tomcat has a version of its runtime that is tested and verified to run on OpenShift. Some components, for example, the Embedded Tomcat Container and the Java container image, are provided as part of a Red Hat subscription when used with Spring Boot Tomcat.

3. Can you give me the details on what you wording you'd like to see here.

**Comment by metacosm** [comment]
@lavernw1 Since the runtime name is changed, the wording of the runtime details obviously needs to be changed to something similar to:

> The RHOAR Spring Boot runtime is tested and verified to run with the Embedded Tomcat Container on OpenShift. This embedded container, as well as other components such as the Java container image, are provided as part of a Red Hat subscription when using the Spring Boot runtime.

**Comment by tradej** [comment]
Closed via #856.
