### ISSUE TITLE
Why do we describe 3 deployment procedures

### ISSUE THREAD

**Issue by cmoulliard** [fabric8-launch/appdev-documentation#782]
Why do we describe 3 deployment procedures while in fact we have only 2 to describe using either zip or automated flow => template ? 

![screenshot 2017-11-06 16 21 04](https://user-images.githubusercontent.com/463790/32448229-a2757008-c30e-11e7-8ee4-b4b0845b0fa5.png)

**Comment by rhoads-zach** [comment]
@cmoulliard these describe how to deploy the booster to each of those environments. Within each section we cover the zip and automated flow.

**Comment by cmoulliard** [comment]
> those environments

This create a lot of redundancies when finally the process using f-m-p to deploy a project on Openshift (Online, local) is always the same.

**Comment by rhoads-zach** [comment]
@cmoulliard when organizing the docs, we took a modular approach for creating content. While it can look redundant when reading end-to-end, it is helpful for users jumping directly into the sections. It gives them everything they need without having to jump across sections or switch mental contexts.

FYI @tradej 

closing this issue
