### ISSUE TITLE
ConfigMap mission / Spring Boot: incorrect instructions

### ISSUE THREAD

**Issue by metacosm** [fabric8-launch/appdev-documentation#787]
Sections 2.2.1.3 / 2.2.2.4
Step 4 of procedure using oc cli should use file:
`greeting-service/src/main/etc/application.properties` instead of `src/main/etc/application.properties` (that last file doesn't exist anymore).

**Comment by metacosm** [comment]
Note that this fix wouldn't be needed if we used instructions as detailed in #786

**Comment by lavernw1** [comment]
@metacosm will  change in  [#786](https://github.com/fabric8-launch/appdev-documentation/issues/786) work across all missions. If so we will  consider implementing this one based on decision on https://github.com/fabric8-launch/appdev-documentation/issues/786.
