### ISSUE TITLE
Integration tests: Add requirement to run IT's in a dedicated project to avoid accidental app deletion.

### ISSUE THREAD

**Issue by inoxx03** [fabric8-launch/appdev-documentation#813]
The steps for executing integration tests should include the prerequisite to run the test in a separate OpenShift project, as executing the integration test in a project already containing an application will cause that application to be removed.
Alternatively we could provide a note instead of the prerequisite.

@Ladicek @tradej FYI^^

**Comment by Ladicek** [comment]
That also happens with Arquillian Cube, and I'm not 100% sure it's a big deal.

**Comment by inoxx03** [comment]
@Ladicek As you said, it does not seem to be a major issue, but I'd rather we include a note about it, just to be on the safe side:)

**Comment by Ladicek** [comment]
Yea agree there should be a note/warning that this happens. Just want to point out that there's no difference between OSTA and Arquillian Cube here.
