### ISSUE TITLE
Remove the Hollow JAR chapter and references to it

### ISSUE THREAD

**Issue by tradej** [fabric8-launch/appdev-documentation#823]
Make the references to the chapter conditional when the `:product:` attribute is not set.

**This change must be committed to the upstream WFS repository and then synced to this one.**

**Comment by tradej** [comment]
Upstrream PR filed at wildfly-swarm/wildfly-swarm#689.

**Comment by tradej** [comment]
Still waiting for the upstream PR to be accepted.

**Comment by rhoads-zach** [comment]
resolved in #872
