### ISSUE TITLE
SpringBoot: Appendix B: Breakdown of POM Components

### ISSUE THREAD

**Issue by liborfuka** [fabric8-launch/appdev-documentation#829]
Update this appendix regarding SpringBoot 1.5.8.RELEASE version which we will deliver.
See https://github.com/snowdrop/spring-boot-http-booster/tree/sb-1.5.x
or product redhat branch: https://github.com/snowdrop/spring-boot-http-booster/tree/redhat

**Comment by metacosm** [comment]
I believe this is a duplicate of #761

**Comment by rhoads-zach** [comment]
closing as duplicate
