### ISSUE TITLE
SSO Booster: Demoapp client is not longer used 

### ISSUE THREAD

**Issue by cmoulliard** [fabric8-launch/appdev-documentation#835]
The demoapp section should be removed as we don't use it anymore

![screenshot 2017-11-08 18 34 22](https://user-images.githubusercontent.com/463790/32564136-8b628d14-c4b3-11e7-83a0-cecbadc9670c.png)

**Comment by tradej** [comment]
I'm taking this. This issue is related to #802.

**Comment by cmoulliard** [comment]
The curl request still use it .... That should be clarified to avoid to confuse the user. Do we need it or can we use "secured-booster-endpoint" client to get the token ?

**Comment by tradej** [comment]
@cmoulliard, does that mean that the demoapp client is still in use and should stay documented, and therefore this issue can be closed without making any changes? Thanks.

**Comment by tradej** [comment]
The answer is yes. Closing.
