### ISSUE TITLE
[Vert.x] Runtime information section: fix wording around vertx maven plugin

### ISSUE THREAD

**Issue by inoxx03** [fabric8-launch/appdev-documentation#836]
The guide currently says:

> Reference vertx-maven-plugin as a dependency for your application.

this is inaccurate and should be changed to:

> Reference vertx-maven-plugin as a plugin to be used for packaging your application.

NOTE: this is the prescribed way of packaging apps developed with RHOAR, but i is by no means a the only way:)

**Comment by inoxx03** [comment]
resolved in PR #853

**Comment by rhoads-zach** [comment]
fixed in #853
