### ISSUE TITLE
incorrect identifiers in Swarm "4.6.7. Interacting with the Secured Booster"

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launch/appdev-documentation#848]
This chapter uses `secured-wf-http` as an identifier of the route/service, but that's wrong. The correct one is `wfswarm-rest-http-secured`.

**Comment by metacosm** [comment]
Same issue with Spring Boot.

**Comment by metacosm** [comment]
I would say the priority is high since you won't be able to run the commands without the proper service name (which granted can be found with `oc get routes`).

**Comment by Ladicek** [comment]
Yea, well, it's a typo and I guess users can easily figure that out. If there was "medium", I'd put "medium" priority :-) But raising to high.

**Comment by metacosm** [comment]
By the way, this is not a typo, the documentation code expects a `secured-{parameter-runtime}-http` format for the service, which isn't the case anymore.

**Comment by Ladicek** [comment]
Right, it's not a typo in the source code, but in the final form, it looks like one.

**Comment by tradej** [comment]
The same is valid for Spring Boot and the REST API mission.
