### ISSUE TITLE
Add integration test instructions for all boosters

### ISSUE THREAD

**Issue by inoxx03** [fabric8-launch/appdev-documentation#852]
Some of the booster docs in the vert.x Runtime guide are currently missing an integration test section.
Since all boosters have integration tests available, instructions for running them should be included with every booster.

Currently, Integration Test docs are missing from the following missions:

* HTTP API Level 0
* ConfigMap
* Health Check

The Relational Database and Circuit Breaker missions have docs on running Integration tests, but the sections are inconsistent in content and structure.

The Secured mission Integration test instructions are modularized.

*This issue does not apply to Node,js Missions*

**Comment by inoxx03** [comment]
@Ladicek assuming that all the integrations test use OpenShift Test Assistant,
What are the steps for executing the tests for the HTTP API, ConfigMap and Health Check boosters.
Can we use `mvn clean verify -Popenshift,openshift-it` for all of them?

**Comment by Ladicek** [comment]
Some boosters tests use OSTA and some use Arquillian Cube and they can all be executed using `mvn clean verify -Popenshift,openshift-it` (except of the SSO booster, that has special instructions).

**Comment by inoxx03** [comment]
resolved in PR: #859

**Comment by rhoads-zach** [comment]
fixed #859
