### ISSUE TITLE
Remove POM file breakdown section form Runtime Guides

### ISSUE THREAD

**Issue by inoxx03** [fabric8-launch/appdev-documentation#854]
incorporates: #761

The the POM File Breakdown section of the Runtime Guides in currently not suitable for publishing due to the following reasons: 

* The contents of the pom file used in the example are outdated and would require extensive updates before being publishable.

* The  file that we use as the general example is sourced from the HTTP API booster's `pom.xml` file.
While this is good as a general example, it does not cover all the POM file specifics for different boosters. 

The docs team has agreed to remove the section until it can be refactored and updated, after which it can be reintroduced to the guides.

@tradej @lavernw1 @ccopelloRH @rhoads-zach ^^ FYI

*Standard disclaimer: This issue does not apply to the Node.js runtime.*

**Comment by lavernw1** [comment]
@inoxx03  I initially  thought you were adding a new issue to cover re-factoring the POM section for boosters. Is this issure for the refactor or removal of the POMs? Should I obsolete or close my related issue[ 761 ](https://github.com/fabric8-launch/appdev-documentation/issues/761)for Spring Boot POM

**Comment by inoxx03** [comment]
@lavernw1 This issue is for the removal of the section for all runtime guides.
We can file a follow-up issue to refactor and reintroduce the section in a subsequent docs release.

**Comment by inoxx03** [comment]
resolved by PR #855
