### ISSUE TITLE
known issues in WildFly Swarm for Release Notes

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launch/appdev-documentation#888]
I'd like to have these known issues documented in Release Notes for WildFly Swarm:

- Ribbon Secured fraction doesn’t work (ENTSWM-211)
- Can’t use Apache HTTP Client or JAX-RS Client in a test without manually specifying Commons Logging version (ENTSWM-220)
- Swarm Arquillian adapter ignores mvn -s settings.xml (SWARM-1546)

Unlike e.g. ENTVTX, ENTSWM isn't public, so probably want to include some details in the release notes text. Just ping me if you wanna help with that.

**Comment by Ladicek** [comment]
CC @tradej

**Comment by inoxx03** [comment]
@Ladicek Section updated. Thank you for the review:) Closing.
