### ISSUE TITLE
Broken link (404) for Automated Script

### ISSUE THREAD

**Issue by rafabene** [fabric8-launch/appdev-documentation#901]
5.1. Creating Fabric8 Launcher Service Using Automated Script

The link to the automated script points to https://raw.githubusercontent.com/fabric8-launch/appdev-documentation/master/scripts/deploy_launchpad_mission.sh which is not present

**Comment by rhoads-zach** [comment]
thank you @rafabene, it is fixed here:
https://appdev.prod-preview.openshift.io/docs/minishift-installation.html#install-launcher-app
