### ISSUE TITLE
include the note about keycloak-authz-client-2.5.14.Final-redhat-1 being tech preview in Spring Boot release notes

### ISSUE THREAD

**Issue by Ladicek** [fabric8-launch/appdev-documentation#919]
The Spring Boot Maven repo we ship contains the `keycloak-authz-client-2.5.14.Final-redhat-1` artifact, which is tech preview, so we need to include that note in Spring Boot release notes. Similarly to what we do with WildFly Swarm.

**Comment by inoxx03** [comment]
@Ladicek I listed `keycloak-authz-client-2.5.14.Final-redhat-1` as tech preview for both WilldFlySwarm and Springboot: 

WFS section: https://doc-stage.usersys.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html-single/red_hat_openshift_application_runtimes_release_notes/#maven-artifacts-wf-swarm-tech-preview

SB section: https://doc-stage.usersys.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html-single/red_hat_openshift_application_runtimes_release_notes/#maven-artifacts-spring-boot-tech-preview

The RN also contain a general notice about tech preview components that links to Red Hat's Limited Support Scope Statement and mention s that all components designated as tech preview are subject to limits on  supportability specified in the aforementioned statement. 

WDYT?

**Comment by Ladicek** [comment]
LGTM, thanks!

**Comment by Ladicek** [comment]
(Not sure why tech preview artifacts are listed before fully supported ones, but whatever :-) )

**Comment by inoxx03** [comment]
@ladicek Good point. I figured that the sequence in which they are listed is not that critical. But it makes sense to have them at the end of the runtime artifacts sections  rather than at the beginning. Let me fix that:) Thank you:)

**Comment by Ladicek** [comment]
Yea it's not a big deal, but it looks strange :-)

**Comment by inoxx03** [comment]
@Ladicek Done I moved the tech preview component tables to the end of their respective runtime chapters. IMHO the structure looks a little better now:)

**Comment by inoxx03** [comment]
resolved. Closing this issue

**Comment by Ladicek** [comment]
Thanks @inoxx03, LGTM :-)
