### ISSUE TITLE
Typo in Spring Boot Runtime Guide

### ISSUE THREAD

**Issue by ccopelloRH** [fabric8-launch/appdev-documentation#929]
Spring Boot Runtime Guide on Preview. In Chapter 1, SB Tested and Verified Version section, is this sentence:

This embedded container, as well as other components such as the Java container image, **are** provided as part of a Red Hat subscription when used with Spring Boot.

should "are" be "is"?

**Comment by lavernw1** [comment]
@ccopelloRH fixed typo

**Comment by lavernw1** [comment]
@ccopelloRH changes incorporated.
