### ISSUE TITLE
Spring Boot Guide: Versions section needs link to RN component versions table for Spring Boot tested starters

### ISSUE THREAD

**Issue by ccopelloRH** [fabric8-launch/appdev-documentation#930]
Here is the production RN URL: [https://access.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html-single/red_hat_openshift_application_runtimes_release_notes/]

This issue is for [https://issues.jboss.org/browse/OBST-500].

**Comment by lavernw1** [comment]
Added link to RN in SB runtime guide.

**Comment by lavernw1** [comment]
@ccopelloRH changse incorporated and merged.
