### ISSUE TITLE
Capitalization Question: Single-node or Single-Node?

### ISSUE THREAD

**Issue by ccopelloRH** [fabric8-launch/appdev-documentation#932]
[https://access.qa.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html-single/red_hat_openshift_application_runtimes_release_notes/#deployment-platfroms]

In CDK paragraph, is capitalization correct?

**Comment by inoxx03** [comment]
@ccopelloRH AFAIK, we use `Single-node OpenShift Cluster` in the [doc attributes](https://gitlab.cee.redhat.com/red-hat-openshift-application-runtimes-documentation/rhoar-release-notes/raw/master/docs/topics/templates/document-attributes.adoc).

The capitalization is not correct. Thanks for catching this:) I'll swap the text out for a variable.

**Comment by inoxx03** [comment]
Fixed.
