### ISSUE TITLE
Punctuation: Period instead of exclamation

### ISSUE THREAD

**Issue by ccopelloRH** [fabric8-launch/appdev-documentation#933]
[https://access.qa.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html-single/red_hat_openshift_application_runtimes_release_notes/#deployment-platfroms]

In OpenShift Container Platform, it may be better to use a period instead of exclamation point.

**Comment by inoxx03** [comment]
Thank you:) Fixed.
