### ISSUE TITLE
Eclipse Vert.x Sentence Structure

### ISSUE THREAD

**Issue by ccopelloRH** [fabric8-launch/appdev-documentation#934]
[https://access.qa.redhat.com/documentation/en-us/red_hat_openshift_application_runtimes/1/html-single/red_hat_openshift_application_runtimes_release_notes/#rn-runtime-components-vertx]

Currently: "The Eclipse Vert.x runtime artifacts provided with this release of RHOAR are based all on upstream version 3.4.2."

What do you think about "The Eclipse Vert.x runtime artifacts provided with this release of RHOAR are all based on upstream version 3.4.2."

Placing "all" before "based"

**Comment by inoxx03** [comment]
Thank you:) Fixed.
